import {
	cyan,
	cyanDark,
	grass,
	grassDark,
	purple,
	purpleDark,
	red,
	redDark,
	slate,
	slateDark,
} from "@radix-ui/colors";

import { UNIT_CATEGORY } from "@dazzlegarden/types/imdf";

// enum IMDF_UNIT_SUBCATEGORY {
// 	elevation = "#83a7bd",
// 	structure = "#aba7a2",
// 	health = "#eea3a3",
// 	nonpublic = "#a4a4a4",
// 	opentobelow = "#c9b7b7",
// 	road = "#b2b7bc",
// 	restroom = "#cca8d4",
// 	green = "#a8d4a8",
// 	unspecified = "#d4d4d4",
// }
export enum IMDF_UNIT_SUBCATEGORY {
	elevation = 1,
	structure,
	health,
	nonpublic,
	unenclosedarea,
	opentobelow,
	road,
	restroom,
	green,
	walkway,
	unspecified,
}

export const IMDF_UNIT_COLOR: Record<IMDF_UNIT_SUBCATEGORY, [string, string]> =
	{
		[IMDF_UNIT_SUBCATEGORY.elevation]: [cyan.cyan3, cyanDark.cyan4],
		[IMDF_UNIT_SUBCATEGORY.structure]: [slate.slate6, slateDark.slate10],
		[IMDF_UNIT_SUBCATEGORY.health]: [red.red4, redDark.red4],
		[IMDF_UNIT_SUBCATEGORY.nonpublic]: [slate.slate6, slateDark.slate4],
		[IMDF_UNIT_SUBCATEGORY.unenclosedarea]: [slate.slate3, slateDark.slate3],
		[IMDF_UNIT_SUBCATEGORY.opentobelow]: [slate.slate2, slateDark.slate2],
		[IMDF_UNIT_SUBCATEGORY.road]: [slate.slate2, slateDark.slate2],
		[IMDF_UNIT_SUBCATEGORY.restroom]: [purple.purple3, purpleDark.purple4],
		[IMDF_UNIT_SUBCATEGORY.green]: [grass.grass4, grassDark.grass4],
		[IMDF_UNIT_SUBCATEGORY.walkway]: [slate.slate1, slateDark.slate8],
		[IMDF_UNIT_SUBCATEGORY.unspecified]: [slate.slate4, slateDark.slate6],
		// structure = "aba7a2",
		// health = "eea3a3",
		// nonpublic = "a4a4a4",
		// opentobelow = "c9b7b7",
		// road = "b2b7bc",
		// restroom = "cca8d4",
		// green = "a8d4a8",
		// unspecified = "slate",
	};

export const IMDF_UNIT_SUBCATEGORIES: Record<
	UNIT_CATEGORY,
	IMDF_UNIT_SUBCATEGORY
> = {
	auditorium: IMDF_UNIT_SUBCATEGORY.unspecified,
	classroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	conferenceroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	fieldofplay: IMDF_UNIT_SUBCATEGORY.unspecified,
	fitnessroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	foodservice: IMDF_UNIT_SUBCATEGORY.unspecified,
	footbridge: IMDF_UNIT_SUBCATEGORY.unspecified,
	huddleroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	kitchen: IMDF_UNIT_SUBCATEGORY.unspecified,
	laboratory: IMDF_UNIT_SUBCATEGORY.unspecified,
	library: IMDF_UNIT_SUBCATEGORY.unspecified,
	lobby: IMDF_UNIT_SUBCATEGORY.unspecified,
	lounge: IMDF_UNIT_SUBCATEGORY.unspecified,
	mailroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	movietheater: IMDF_UNIT_SUBCATEGORY.unspecified,
	office: IMDF_UNIT_SUBCATEGORY.unspecified,
	phoneroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	platform: IMDF_UNIT_SUBCATEGORY.unspecified,
	privatelounge: IMDF_UNIT_SUBCATEGORY.unspecified,
	recreation: IMDF_UNIT_SUBCATEGORY.unspecified,
	room: IMDF_UNIT_SUBCATEGORY.unspecified,
	serverroom: IMDF_UNIT_SUBCATEGORY.unspecified,
	smokingarea: IMDF_UNIT_SUBCATEGORY.unspecified,
	storage: IMDF_UNIT_SUBCATEGORY.unspecified,
	terrace: IMDF_UNIT_SUBCATEGORY.unspecified,
	theater: IMDF_UNIT_SUBCATEGORY.unspecified,
	unspecified: IMDF_UNIT_SUBCATEGORY.unspecified,
	waitingroom: IMDF_UNIT_SUBCATEGORY.unspecified,

	elevator: IMDF_UNIT_SUBCATEGORY.elevation,
	escalator: IMDF_UNIT_SUBCATEGORY.elevation,
	movingwalkway: IMDF_UNIT_SUBCATEGORY.elevation,
	ramp: IMDF_UNIT_SUBCATEGORY.elevation,
	stairs: IMDF_UNIT_SUBCATEGORY.elevation,
	steps: IMDF_UNIT_SUBCATEGORY.elevation,

	brick: IMDF_UNIT_SUBCATEGORY.structure,
	column: IMDF_UNIT_SUBCATEGORY.structure,
	concrete: IMDF_UNIT_SUBCATEGORY.structure,
	drywall: IMDF_UNIT_SUBCATEGORY.structure,
	glass: IMDF_UNIT_SUBCATEGORY.structure,
	structure: IMDF_UNIT_SUBCATEGORY.structure,
	wood: IMDF_UNIT_SUBCATEGORY.structure,

	firstaid: IMDF_UNIT_SUBCATEGORY.health,

	nonpublic: IMDF_UNIT_SUBCATEGORY.nonpublic,
	unenclosedarea: IMDF_UNIT_SUBCATEGORY.unenclosedarea,
	opentobelow: IMDF_UNIT_SUBCATEGORY.opentobelow,
	parking: IMDF_UNIT_SUBCATEGORY.road,
	road: IMDF_UNIT_SUBCATEGORY.road,
	vegetation: IMDF_UNIT_SUBCATEGORY.green,

	restroom: IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.family": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.female": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.female.wheelchair": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.male": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.male.wheelchair": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.transgender": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.transgender.wheelchair": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.unisex": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.unisex.wheelchair": IMDF_UNIT_SUBCATEGORY.restroom,
	"restroom.wheelchair": IMDF_UNIT_SUBCATEGORY.restroom,
	shower: IMDF_UNIT_SUBCATEGORY.restroom,
	mothersroom: IMDF_UNIT_SUBCATEGORY.restroom,

	walkway: IMDF_UNIT_SUBCATEGORY.walkway,
	"walkway.island": IMDF_UNIT_SUBCATEGORY.walkway,
};
